# Generated by Django 5.1.6 on 2025-02-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_desc',
            field=models.CharField(default=1, max_length=9999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resumes/PDFs/'),
        ),
    ]
