# Generated by Django 5.1.6 on 2025-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_job_desc_alter_resume_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Resume',
            old_name='job_desc',
            new_name='job_description')
    ]
