# Generated by Django 5.1.6 on 2025-02-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_resume_job_desc_resume_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_description',
            field=models.TextField(),
        ),
    ]
